Typos and quotes fixed

diff --git a/etc/init.d/ipset-persistent b/etc/init.d/ipset-persistent
--- a/etc/init.d/ipset-persistent
+++ b/etc/init.d/ipset-persistent
@@ -36,11 +36,13 @@ RETVAL=0
 checks()
 {
     # Checking for ipset binary
-    if [ ! -x $IPSET_BIN ]; then
-        log_failure_msg "Command ipset is defined in $DEFAULTS, but not found or is not executable. Please fix or remove definition."
-        exit 1
+    if [ ! -z "$IPSET_BIN" ]; then
+        if [ ! -f "$IPSET_BIN" ] || [ ! -x "$IPSET_BIN" ]; then
+            log_failure_msg "Command ipset is defined in $DEFAULTS, but not found or is not executable. Please fix or remove definition."
+            exit 1
+        fi
     fi
-    if [ -z $IPSET_BIN ]; then
+    if [ -z "$IPSET_BIN" ]; then
         if ! hash ipset &>/dev/null; then 
             log_failure_msg "Command ipset not found in PATH - please define it in $DEFAULTS"
             exit 1
@@ -49,7 +51,7 @@ checks()
         fi
     fi
     # Checking if directory for sets presents
-    if [ ! -d $CONF_DIR ]; then
+    if [ ! -d "$CONF_DIR" ]; then
         log_failure_msg "Directory '$CONF_DIR' doesn't exists - can't continue"
         exit 1
     fi
@@ -59,22 +61,28 @@ load_sets()
 {
     log_action_begin_msg "Loading ipset sets"
 
-    if [ $IP_SPLIT_CONFIG == "yes" ]; then
+    if [ "$IP_SPLIT_CONFIG" == "yes" ]; then
         $IPSET_BIN flush
-        for filename in "$CONF_DIR/*.set"; do
-            $IPSET_BIN restore -exist < "$filename"
-            if [ $? -ne 0 ]; then
-                RETVAL=1
-                log_action_cont_msg " $filename - FAILED"
-            else
-                log_action_cont_msg " $filename loaded"
+        for filename in $CONF_DIR/*.set; do
+            if [ -f "$filename" ]; then
+                $IPSET_BIN restore -exist < "$filename"
+                if [ $? -ne 0 ]; then
+                    RETVAL=1
+                    log_action_cont_msg " $filename - FAILED"
+                else
+                    log_action_cont_msg " $filename loaded"
+                fi
             fi
         done
     else
         $IPSET_BIN flush
-        $IPSET_BIN restore -exist < "$CONF_DIR/$CONF_NAME"
-        if [ $? -ne 0 ]; then
-            RETVAL=1
+        if [ -f "$CONF_DIR/$CONF_NAME" ]; then
+            $IPSET_BIN restore -exist < "$CONF_DIR/$CONF_NAME"
+            if [ $? -ne 0 ]; then
+                RETVAL=1
+            fi
+        else
+            log_action_cont_msg " configuration $CONF_DIR/$CONF_NAME doesn'e exists - skipping"
         fi
     fi
 
@@ -85,7 +93,7 @@ save_sets()
 {
     log_action_begin_msg "Saving ipset sets"
 
-    if [ $IP_SPLIT_CONFIG == "yes" ]; then
+    if [ "$IP_SPLIT_CONFIG" == "yes" ]; then
         for setname in `ipset list -n`; do
             $IPSET_BIN save $setname > "$CONF_DIR/$setname.set"
             if [ $? -ne 0 ]; then
